### ISSUE TITLE
Gamemode crashes when player joins

### ISSUE THREAD

**Issue by Joaquel** [parkour-tf/ParkourFortress-Redux#2]
When changing gamemode to PF, all resources are added to the download table (sounds, models and textures), but when the person joins, server crashes (the player does not get to fully enter the server, it stays on the loading screen as seen in the next picture):

![image](https://user-images.githubusercontent.com/45585078/147448781-797d2de7-b0de-4b5c-aab9-07ef2dc76bfc.png)

A thing to mention, is that when the plugin is loaded, this error appears in the console:
```
L 12/27/2021 - 04:52:03: [SM] Exception reported: Invalid convar handle 0 (error 4)
L 12/27/2021 - 04:52:03: [SM] Blaming: parkourfortress.smx
L 12/27/2021 - 04:52:03: [SM] Call stack trace:
L 12/27/2021 - 04:52:03: [SM]   [0] ConVar.SetFloat
L 12/27/2021 - 04:52:03: [SM]   [1] Line 204, C:\Users\user\AppData\Roaming\spcode\sourcepawn\configs\sm_1_10_0_6509\parkourfortress.sp::OnAllPluginsLoaded
```

Additional info:
Using Metamod:Source version 1.11.0-dev+1143
Same Sourcemod version (SourceMod 1.10.0.6512)
Latest TF Econ Data version (0.18.1 version)
Latest DHooks version (also tried version 8)

Entering to the map with the plugin unloaded and loading it through rcon loads the gamemode (not everything works as it should).

**Comment by namishere** [comment]
The server makes use of a third party plugin to reveal and uncap the hidden cvar `tf_maxspeed_limit`. If you were to add [said plugin](https://github.com/FlaminSarge/tf_maxspeed_patch) to your server, this error would be resolved. This is obviously not an ideal solution, of course. With that in mind, there's a couple solutions I can think of off the top of my head:

> Add this plugin to the list of dependencies
> Migrate to a generalized memory patch system, possibly Source Scramble (this would add another dependency, however)
> Rewrite this plugin and integrate it into our own

I'll gather some opinions from the team on what the best course of action is, but for now I'm going to go with solution 1. Will leave this open in the meanwhile.

**Comment by namishere** [comment]
Are you able to successfully join a server with the plugin active after 860e048?

**Comment by Joaquel** [comment]
> Are you able to successfully join a server with the plugin active after [860e048](https://github.com/parkour-tf/ParkourFortress-Redux/commit/860e0488aec7e9d9b621e4761982c7a67c1c2a4a)?

Nope, still crashing.
Also: L 12/29/2021 - 21:41:05: [parkourfortress.smx] Value at (0x15505859) was not expected: (5200.0000) != 520.0. Cowardly refusing to do things.

**Comment by OO0000O** [comment]
I think there is a problem with the game data for windows version. I removed parkourdata.txt and the server no longer crashes. The first person motion throws an error, but the rest works fine.

**Comment by namishere** [comment]
That's very strange... the plugin explicitly tries to load parkourdata.txt in InitSDK(), and if it's not found the plugin will automatically halt further execution. Asides from that, a good portion of the plugin functionality relies on hooks provided by said gamedata, so I'm deeply unsure how the plugin would even work correctly with it missing.

**Comment by Joaquel** [comment]
Last version doesn't works directly, it says this when loading:

`L 12/31/2021 - 04:49:45: [SM] Exception reported: Hook not setup for a detour.
L 12/31/2021 - 04:49:45: [SM] Blaming: parkourfortress.smx
L 12/31/2021 - 04:49:45: [SM] Call stack trace:
L 12/31/2021 - 04:49:45: [SM]   [0] DHookEnableDetour
L 12/31/2021 - 04:49:45: [SM]   [1] Line 703, C:\Users\link7\AppData\Roaming\spcode\sourcepawn\configs\sm_1_10_0_6509\parkourfortress.sp::InitSDK
L 12/31/2021 - 04:49:45: [SM]   [2] Line 141, C:\Users\link7\AppData\Roaming\spcode\sourcepawn\configs\sm_1_10_0_6509\parkourfortress.sp::OnPluginStart
[SM] Plugin parkourfortress.smx failed to load: Error detected in plugin startup (see error logs).`

**Comment by worMatty** [comment]
When I run the plugin on a Windows server, it crashes when I join. However, on Linux it does not.

Enviro deets: Tested on my Windows 11 machine in Win and via WSL. Tested on a Linux VPS. 
All dependencies installed including FlaminSarge's max speed patch. 

https://crash.limetech.org/e37pqbsd2ip4

**Comment by gdfsgdfg** [comment]
Crashes instantly when I try to join the server as well. Windows server.

**Comment by ScrewdriverHyena** [comment]
We will work on this for a coming future release. Apologies for the long wait.

**Comment by gdfsgdfg** [comment]
Good news windows build seems to work now.

However I can't seem to able to jump again when trying to climb or after running on walls.

**Comment by horiuchii** [comment]
Should be retested as of commit 68eca7411b1a579f341974877d468d59454c621b.

**Comment by poetatellus** [comment]
Running windows server, tested with version downloaded last week, and version just downloaded. Always crashes on player loading in. Can load the plugin mid round and it works, but if anyone new tries to spawn, the server crashes. Removed all but basic sourcemod plugins and issue persisted. Tried without gamedata as other person claimed, no crash, but of course limited functionality.

```
L 01/17/2023 - 19:30:23: [disabled\parkourfortress.smx] Value at (0x180AF879) was not expected: (5200.0000) != 520.0. Cowardly refusing to do things.
```

**Comment by horiuchii** [comment]
Could you send a link to a crash log generated via [Accelerator](https://forums.alliedmods.net/showthread.php?t=277703)?

**Comment by poetatellus** [comment]
https://crash.limetech.org/rouw3vklisbv
