### ISSUE TITLE
Flying/Noclip is interruptible and doesn't unlock controls

### ISSUE THREAD

**Issue by ZwipZwapZapony** [parkour-tf/ParkourFortress-Redux#21]
When using `sm_timer` to disable the timer and `sm_fly` to enable noclip mode, noclip is deactivated when entering or leaving a start/spawn area, colliding with a climable pipe/ladder, maybe some other things as well. This makes noclip less reliable.

Additionally, if a `"lockcontrols"` map trigger disabled the player's controls, noclip doesn't re-enable controls, meaning that the player can get stuck without control. Noclip should re-enable the player's controls (even after noclipping ends, in case that the player flew away from the `"unlockcontrols"` trigger).

**Comment by horiuchii** [comment]
Seems to be completely resolved as of the latest commit.
