### ISSUE TITLE
[Suggestion] "No PF music" map entity

### ISSUE THREAD

**Issue by ZwipZwapZapony** [parkour-tf/ParkourFortress-Redux#25]
Some maps (Darker Meat, Edge, Sonic, et cetera) contain their own built-in music. Allowing such maps to have an entity that disables Parkour Fortress' music (like the `sm_pf_music` console command) would be nice, to avoid "stacked" music.

**Comment by horiuchii** [comment]
Resolved in commit 014cbe0889b5d61b96f30023ecc8af5405315101

Maps now look for an info_target named "pf_musicplayer" to determine if the map has music to display a custom message telling the user how to avoid "stacked" music.

Legacy maps will utilize a new cfg file to determine if they should display the warning or not.
