### ISSUE TITLE
I can not build project with this repository.

### ISSUE THREAD

**Issue by jobggun** [parkour-tf/ParkourFortress-Redux#27]
I tried to build this project with spcomp, but i failed with many errors.
Is there any latest source or guide to build? 
Thank you.

**Comment by horiuchii** [comment]
Could you please share your compile log in a [gist](https://gist.github.com/) so that I may better help you with your issue?

**Comment by jobggun** [comment]
> Could you please share your compile log in a [gist](https://gist.github.com/) so that I may better help you with your issue?

https://gist.github.com/jobggun/3b661f5de3fde43bea7ce8be6132aa03

here is my compile log(s)
actually this compile error can be resolved with commenting out some statements and changing symbol
however after resoving this (log1), another problem shows up

i am afraid that i do not believe this is the version which is in the parkour.tf servers

Thank you

**Comment by horiuchii** [comment]
Is the compile log any different when using the latest version of sourcemod 1.12?

**Comment by horiuchii** [comment]
All of these errors should be fixed as of commit 68eca7411b1a579f341974877d468d59454c621b, closing for now.
