### ISSUE TITLE
Player can't move in place

### ISSUE THREAD

**Issue by TYHH100** [parkour-tf/ParkourFortress-Redux#30]
Hello, I am a server administrator from China. Recently, we have equipped parkour plug-in on the server. But after running, the players are stuck in place and can't move, but the movement of sarcasm and the function of climbing pipes can work. What's the situation.
Build and play this mode for the first time
mmsource 1.11.0.1148
sourcemod 1.11.0.6927
System Ubuntu 20.04
(My English is not good So this is translated by machine)

**Comment by horiuchii** [comment]
Hello! Could you test the latest version of the plugin again to see if the same issues still exist?

**Comment by TYHH100** [comment]
> Hello! Could you test the latest version of the plugin again to see if the same issues still exist?
Thank you for your reply
After testing, win and Linux have not found any problems so far
