### ISSUE TITLE
Hands can not be seen.

### ISSUE THREAD

**Issue by Learner10** [parkour-tf/ParkourFortress-Redux#32]
Seems that recently, the hand animations are not drawn on the player's screen anymore. Some folks also said other similar sensual details have gone missing too, but as of right now, the most readily obvious issue is the hand animations can not be seen.

**Comment by horiuchii** [comment]
Does typing `pf_viewmodel` in the client console do anything?

**Comment by Learner10** [comment]
Seems it has. Strange how it's been toggled off. Is there anywhere with the list of Parkour Fortress commands?

**Comment by horiuchii** [comment]
> Is there anywhere with the list of Parkour Fortress commands?

https://github.com/parkour-tf/ParkourFortress-Redux/blob/main/tf/addons/sourcemod/scripting/parkourfortress.sp#L161-L207

This is the list of PF commands, I will also be closing this issue as it seems to be resolved.
