### ISSUE TITLE
Viewmodels not downloading for new/returning players

### ISSUE THREAD

**Issue by Scuram** [parkour-tf/ParkourFortress-Redux#38]
For some reason new players don't have the pf animations when they join, and they all see an error on their screen until they disable them.
This doesn't seem to be a rare case, every new player I've seen has complained about this.

**Comment by horiuchii** [comment]
Needs a retest after latest commit

**Comment by ScrewdriverHyena** [comment]
Let me know if this is still happening.

**Comment by horiuchii** [comment]
Closing as no further incidents have been reported post fix.
